#ifndef _APPS_H_
#define _APPS_H_

#define APPS_1_PIN 41
#define APPS_2_PIN 40

#define APPS_1_UPPER_BOUND 1023
#define APPS_1_LOWER_BOUND 9

#define APPS_2_UPPER_BOUND 1020
#define APPS_2_LOWER_BOUND 0

#define APPS1_DEAD_THRESHOLD 1020
#define APPS2_DEAD_THRESHOLD 3

#define APPS1_DEADZONE_EQUIVALENT 820
#define APPS2_DEADZONE_EQUIVALENT 225

#define APPS_LINEAR_OFFSET 220
#define APPS_INITIAL_TRIGGER 1000

#define APPS_MAX_ERROR_PERCENT (10 - 1.173)
#define APPS_MAX_ERROR_ABS (APPS_1_UPPER_BOUND * APPS_MAX_ERROR_PERCENT / 100)

#define AVG_SAMPLES 6

#define APPS_IMPLAUSIBLE_TIMEOUT_MS 500

#define BAMOCAR_MAX 32760
#define BAMOCAR_ATTENUATION_FACTOR 1

int read_apps();

#endif  // _APPS_H_